Add isort to zeus
TBS-EACPD/zeus pull request #3
Opened 2021-03-09 17:19 UTC by GarvinH

2021-03-09 19:53 UTC, AlexCLeduc commented on dev-requirements.txt
> +factory-boy===2.12.0
can we also bump pylint to 2.6.0 ? pylint 2.5.2  dependes on an older version of isort and makes pip install throw an error

2021-03-09 19:54 UTC, AlexCLeduc commented on zeus/versioning/core.py
>  from django.db import models
we can apply the sort later, let's focus on the config in this PR

2021-03-09 19:59 UTC, AlexCLeduc requested changes
We should also add a deck in CI

```yaml
# .circleci/config.yml
  format_check:
    docker:
      - image: gcr.io/big-coil-207017/titan-ci:latest
        <<: *gcloud_auth
    steps:
      - attach_workspace:
          at: ./
      - run: env/bin/black --check ./
      - run: env/bin/isort # CHECK COMMAND? 

```

It looks like isort has a [command for this](https://github.com/PyCQA/isort#the---check-only-option), I'm not sure exactly which args we should pass 

We'll know the command works if this branch fails and the branch off this one that applies isort to all files passes

2021-03-11 16:43 UTC, AlexCLeduc commented
Looks like isort is checking dependencies, 
![Screen Shot 2021-03-11 at 11 00 51 AM](https://user-images.githubusercontent.com/7769215/110816123-0d31cd80-8259-11eb-8fcb-834849422cf1.png)


isort automatically ignores `venv/`. This is a good excuse to start using `venv/` instead, like every other python project (don't know why we ever settled on env). I've renamed the env upstream on master.

Locally, you'll have to reset your env, something like:

```bash
deactivate
rm -rf env/
python3 -m venv venv
```

Once you rebase, you can just replace the isort command to use `venv/bin/isort` instead.

2021-03-11 18:51 UTC, GarvinH commented
I went ahead and updated pylint and pylint-django to their latest versions. Just thought I'd mention that in case

2021-03-11 19:50 UTC, AlexCLeduc approved these changes
Thanks! After merging, can you open another PR that applies isort to all the files?

2021-03-12 17:18 UTC, merged